export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import 'swagger-ui-react/swagger-ui.css';
import './globals.css';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
